# Generated by Django 2.2.1 on 2019-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('bedroom', models.CharField(max_length=20, verbose_name='房厅')),
                ('area', models.CharField(max_length=20, verbose_name='面积')),
                ('direction', models.CharField(max_length=20, verbose_name='朝向')),
                ('floor', models.CharField(max_length=60, verbose_name='楼层')),
                ('unit_price', models.IntegerField(verbose_name='租金')),
                ('message', models.TextField(default='无', verbose_name='详细信息')),
                ('img_address', models.CharField(max_length=255, verbose_name='图片地址')),
                ('userid', models.IntegerField(default=1, verbose_name='用户id')),
                ('release_time', models.CharField(max_length=255, verbose_name='发布时间')),
                ('isFabu', models.BooleanField(default=True, verbose_name='发布是否成功')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '租房',
                'verbose_name_plural': '租房',
                'db_table': 'houseinfo',
            },
        ),
    ]
