# Generated by Django 2.2.1 on 2019-05-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homelink', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='comment',
            field=models.ManyToManyField(related_name='comment', through='index.UserComment', to='index.User'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Location', verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Village', verbose_name='地区'),
        ),
    ]
