# Generated by Django 2.2.1 on 2019-05-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpro',
            name='send_type',
            field=models.CharField(choices=[('register', '邮箱注册'), ('forget', '忘记密码')], max_length=10, verbose_name='发送类型'),
        ),
    ]
