# Generated by Django 2.2.1 on 2019-05-20 16:13

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190520_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvice',
            name='advices',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='用户建议'),
        ),
    ]
