"""
Django settings for rentingHouse project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!=9z2$fhz2of7cp^)6_71i1xbt7e(vbib8(dwg2*+u932!tk4r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # False关闭错误提醒

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # xadmin配置
    'xadmin',
    'crispy_forms',
    # 自定义app应用配置
    'index',
    'homelink',
    # 分页
    'pure_pagination',

    # 富文本
    'DjangoUeditor',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rentingHouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rentingHouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rentHouse',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root3306',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static').replace('\\', '/')
# 配置static本地静态文件路径
# STATICFILES_DIRS = (
#     os.path.join(os.path.join(BASE_DIR, 'static')),
# )


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_DIRS = (
#     os.path.join(BASE_DIR, 'media')
# )


#邮件配置

EMAIL_HOST = 'smtp.163.com'                   #SMTP地址

EMAIL_PORT = 25                               #SMTP端口

# DEFAULT_FROM_EMAIL = 'huamuxiong_2018@163.com'       #用户收到邮件显示的邮箱

EMAIL_HOST_USER = 'huamuxiong_2018@163.com'       #我自己的邮箱

EMAIL_HOST_PASSWORD = 'My962464'                  #我的邮箱授权码

EMAIL_SUBJECT_PREFIX = '[huamuxiong]'            #为邮件Subject-line前缀,默认是'[django]'

EMAIL_USE_TLS = False                             #与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false

EMAIL_FROM = 'huamuxiong_2018@163.com'

#管理员站点

# SERVER_EMAIL = '1760909338@qq.com'

# 分页配置
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,  # 中间显示 5 个页码  prev 1 2 ... 5 6 7 8 9 ... 31 32 next
    'MARGIN_PAGES_DISPLAYED': 2,  # 2 表示前后显示省略号

    'SHOW_FIRST_PAGE_WHEN_INVALID': True,  # 不再页码范围内，显示第一条
}

