# Generated by Django 2.2.1 on 2019-05-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('author', models.CharField(max_length=30, verbose_name='新闻发布者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='新闻发布时间')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='RedWood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('price', models.FloatField(max_length=10, verbose_name='价格')),
                ('type', models.IntegerField(choices=[(1, '传统中式'), (2, '新中式'), (3, '中式风格')], default=0, verbose_name='风格')),
                ('img', models.ImageField(upload_to='images/redwood/')),
                ('state', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '家具',
                'verbose_name_plural': '家具',
                'db_table': 'redwood',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='出生年月')),
                ('headimg', models.ImageField(upload_to='images/user/', verbose_name='头像')),
                ('isActive', models.BooleanField(default=1, verbose_name='激活状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserHistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('redwood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.RedWood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.IntegerField(choices=[(1, '好评'), (2, '中评'), (3, '差评')], verbose_name='满意度')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('redwood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.RedWood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='index.Users')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('redwood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.RedWood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='UserAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='内容')),
                ('reversion', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申诉时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'verbose_name': '用户建议',
                'verbose_name_plural': '用户建议',
                'db_table': 'advice',
            },
        ),
        migrations.AddField(
            model_name='redwood',
            name='collection',
            field=models.ManyToManyField(related_name='user_collect', through='index.UserCollect', to='index.Users'),
        ),
        migrations.AddField(
            model_name='redwood',
            name='comment',
            field=models.ManyToManyField(related_name='user_comment', through='index.UserComment', to='index.Users'),
        ),
        migrations.AddField(
            model_name='redwood',
            name='history',
            field=models.ManyToManyField(related_name='user_history', through='index.UserHistroy', to='index.Users'),
        ),
    ]
